# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "North Sami spellchecker"
se = "Davvisámi čállindárkkisteaddji"
nb = "Nordsamisk stavekontroll"
sv = "Nordsamisk rättstavning"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for North Sami, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
se = "Davvisámi čállindárkkisteaddji ráhkaduvvon giellageavaheddjiin ja Divvun- ja Giellatekno-joavkkuin UiT Norgga árkttalaš universitehtas"
nb = "Stavekontroll for nordsamisk, laga av Divvun- og Giellatekno-gruppene ved UiT Norges arktiske universitet"
sv = "Rättstavning för nordsamiska, utvecklad av Divvun- och Giellatekno-grupperna vid UiT Norges arktiske universitet"

[macos]
system_pkg_id = "no.divvun.MacDivvun.se"

[windows]
system_product_code = "{3D18193F-D912-482B-8D14-7C3B98B92BF6}_is1"
legacy_product_codes = [
    { value = "17CA4FEF-4327-5E63-9E1F-BB34606D8E07", kind = "nsis" },
    { value = "3F030D39-3CB6-476A-A32E-4822A035DDFD", kind = "nsis" },
]
extra_locales = { se-NO = "se", se-SE = "se", se-FI = "se" }

[package.speller]
name = "North Sami"
version = "4.5.1"

[package.grammar]
name = "North Sami"
version = "1.3.0"

[package.tts-text-proc]
name = "North Sami"
version = "0.1.0"
