template = "https://github.com/giellalt/template-lang-und"
rev_id = 255
template_sha = "b36832e6713c79f483aee143e866d6cad5dec90e"

[replacements]
__GLOTTOLOG_ID__ = "nort2671"
__REPO__ = "lang-sme"
__UND2C__ = "se"
__UNDEFINED__ = "North Sami"
__UND__ = "sme"
