template = "https://github.com/giellalt/template-lang-und"
rev_id = 277
template_sha = "c0f383639e245d1daebce6e2006904e442eef1fd"

[replacements]
__GLOTTOLOG_ID__ = "nort2671"
__REPO__ = "lang-sme"
__UND2C__ = "se"
__UNDEFINED__ = "North Sami"
__UND__ = "sme"
